"""Paquete raíz del dominio de GEMA.

Re-exporta todos los símbolos públicos de los submódulos del dominio
para permitir imports planos (``from app.domain import User``).
"""

# Enums
# Entidades
from app.domain.entities import (
    ArticleCategory,
    Asset,
    CatalogArticle,
    Company,
    Location,
    Permission,
    Role,
    User,
    UserPreference,
)
from app.domain.enums import (
    AssetStatus,
    CompanyStatus,
    EstadoIntervencion,
    LocationType,
    MaintenanceType,
    PermissionModule,
    PriorityLevel,
    ReportStatus,
    Theme,
    WorkOrderStatus,
)

# Eventos
from app.domain.events import (
    AssetCreated,
    AssetDecommissioned,
    AssetLocationChanged,
    AssetMaintenanceStarted,
    AssetOutOfService,
    AssetPutInService,
    AssetUpdated,
    CompanyActivated,
    CompanyCancelled,
    CompanyCreated,
    CompanyProfileUpdated,
    CompanySuspended,
    DomainEvent,
    EventProducer,
    LocationCreated,
    LocationMoved,
    PasswordChanged,
    PasswordResetCompleted,
    PasswordResetInitiated,
    RoleAssigned,
    RoleRevoked,
    UserLoggedIn,
    UserRegistered,
    auto_register,
)

# Excepciones
from app.domain.exceptions import (
    AssetCodeExistsError,
    AssetException,
    AssetInvalidTransitionError,
    AssetNotFoundError,
    AssetSerialExistsError,
    AuthException,
    CompanyAlreadyCancelledError,
    CompanyException,
    CompanyNotFoundError,
    CompanyNotSuspendedError,
    CompanySlugExistsError,
    DomainException,
    EmptyAssetCodeError,
    EmptyCompanyNameError,
    EmptyHashedPasswordError,
    EmptyLocationNameError,
    EmptyRoleNameError,
    EmptySerialError,
    InsufficientPermissionsError,
    InvalidCredentialsError,
    InvalidEmailError,
    InvalidSlugError,
    InvalidTokenError,
    InvalidUUIDError,
    LastAdminRevocationError,
    LocationCircularReferenceError,
    LocationException,
    LocationInvalidTypeHierarchyError,
    LocationNotFoundError,
    PermissionException,
    PreferenceException,
    PreferenceNotFoundError,
    PreferenceThemeInvalidError,
    RoleException,
    RoleNameExistsError,
    RoleNotFoundError,
    UserAlreadyExistsError,
    UserInactiveError,
    ValidationException,
    WeakPasswordError,
)

# Value Objects
from app.domain.value_objects import (
    AssetId,
    CompanyId,
    Email,
    HashedPassword,
    IntervencionId,
    LocationId,
    PlainPassword,
    RoleId,
    Slug,
    UserId,
)

__all__ = [
    # Enums
    "AssetStatus",
    "CompanyStatus",
    "EstadoIntervencion",
    "LocationType",
    "MaintenanceType",
    "PermissionModule",
    "PriorityLevel",
    "ReportStatus",
    "Theme",
    "WorkOrderStatus",
    # Eventos
    "AssetCreated",
    "AssetDecommissioned",
    "AssetLocationChanged",
    "AssetMaintenanceStarted",
    "AssetOutOfService",
    "AssetPutInService",
    "AssetUpdated",
    "CompanyActivated",
    "CompanyCancelled",
    "CompanyCreated",
    "CompanyProfileUpdated",
    "CompanySuspended",
    "DomainEvent",
    "EventProducer",
    "LocationCreated",
    "LocationMoved",
    "PasswordChanged",
    "PasswordResetCompleted",
    "PasswordResetInitiated",
    "RoleAssigned",
    "RoleRevoked",
    "UserLoggedIn",
    "UserRegistered",
    "auto_register",
    # Entidades
    "ArticleCategory",
    "Asset",
    "CatalogArticle",
    "Company",
    "Location",
    "Permission",
    "Role",
    "User",
    "UserPreference",
    # Value Objects
    "AssetId",
    "CompanyId",
    "Email",
    "HashedPassword",
    "IntervencionId",
    "LocationId",
    "PlainPassword",
    "RoleId",
    "Slug",
    "UserId",
    # Excepciones
    "AssetCodeExistsError",
    "AssetException",
    "AssetInvalidTransitionError",
    "AssetNotFoundError",
    "AssetSerialExistsError",
    "AuthException",
    "CompanyAlreadyCancelledError",
    "CompanyException",
    "CompanyNotFoundError",
    "CompanyNotSuspendedError",
    "CompanySlugExistsError",
    "DomainException",
    "EmptyAssetCodeError",
    "EmptyCompanyNameError",
    "EmptyHashedPasswordError",
    "EmptyLocationNameError",
    "EmptyRoleNameError",
    "EmptySerialError",
    "InsufficientPermissionsError",
    "InvalidCredentialsError",
    "InvalidEmailError",
    "InvalidSlugError",
    "InvalidTokenError",
    "InvalidUUIDError",
    "LocationCircularReferenceError",
    "LocationException",
    "LocationInvalidTypeHierarchyError",
    "LocationNotFoundError",
    "PermissionException",
    "PreferenceException",
    "PreferenceNotFoundError",
    "PreferenceThemeInvalidError",
    "RoleException",
    "RoleNameExistsError",
    "RoleNotFoundError",
    "LastAdminRevocationError",
    "UserAlreadyExistsError",
    "UserInactiveError",
    "ValidationException",
    "WeakPasswordError",
]
