from typing import Protocol
from uuid import UUID
from app.domain.entities.article_category import ArticleCategory

class ArticleCategoryRepositoryPort(Protocol):
    """Contrato estructural para el repositorio de categorías de artículos."""
    async def get_by_id(self, category_id: UUID, empresa_id: UUID) -> ArticleCategory | None: ...
    async def get_by_name(self, nombre: str, empresa_id: UUID) -> ArticleCategory | None: ...
    async def get_all_by_empresa(self, empresa_id: UUID) -> list[ArticleCategory]: ...
    async def save(self, category: ArticleCategory) -> None: ...
    async def delete(self, category_id: UUID, empresa_id: UUID) -> None: ...