"""activos

Revision ID: 10468db73cf1
Revises: 76e18683cd19
Create Date: 2026-06-12 07:40:04.262108

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10468db73cf1'
down_revision: str | None = '76e18683cd19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('articulo_id', sa.Uuid(), nullable=False),
    sa.Column('ubicacion_id', sa.Uuid(), nullable=True),
    sa.Column('serial_interno', sa.String(length=100), nullable=False),
    sa.Column('codigo_activo', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Enum('operativo', 'en_mantenimiento', 'fuera_de_servicio', 'dado_de_baja', name='assetstatus'), nullable=False),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('valor_monetario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_catalogo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activos_empresa_id'), 'activos', ['empresa_id'], unique=False)
    op.create_index('uq_activos_empresa_codigo_activo_lower', 'activos', ['empresa_id', sa.literal_column('LOWER(codigo_activo)')], unique=True)
    op.create_index('uq_activos_empresa_serial_interno_lower', 'activos', ['empresa_id', sa.literal_column('LOWER(serial_interno)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_activos_empresa_serial_interno_lower', table_name='activos')
    op.drop_index('uq_activos_empresa_codigo_activo_lower', table_name='activos')
    op.drop_index(op.f('ix_activos_empresa_id'), table_name='activos')
    op.drop_table('activos')
    # ### end Alembic commands ###
