"""add_version_to_inventory_part

Revision ID: 112599d8bc95
Revises: 6053b37250c9
Create Date: 2026-07-01 03:53:56.502886

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112599d8bc95'
down_revision: str | None = '6053b37250c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_repuestos', sa.Column('version', sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventario_repuestos', 'version')
    # ### end Alembic commands ###
