"""create_asset_state_log_table

Revision ID: 21784fe300da
Revises: 7da6e3c7cab0
Create Date: 2026-06-26 23:45:23.074058

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21784fe300da'
down_revision: str | None = '7da6e3c7cab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_estados_activos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('estado_anterior', postgresql.ENUM('operativo', 'en_mantenimiento', 'fuera_de_servicio', 'dado_de_baja', name='assetstatus', create_type=False), nullable=True),
    sa.Column('estado_nuevo', postgresql.ENUM('operativo', 'en_mantenimiento', 'fuera_de_servicio', 'dado_de_baja', name='assetstatus', create_type=False), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_estados_activos_activo_id'), 'logs_estados_activos', ['activo_id'], unique=False)
    op.create_index(op.f('ix_logs_estados_activos_empresa_id'), 'logs_estados_activos', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_estados_activos_empresa_id'), table_name='logs_estados_activos')
    op.drop_index(op.f('ix_logs_estados_activos_activo_id'), table_name='logs_estados_activos')
    op.drop_table('logs_estados_activos')
    # ### end Alembic commands ###
