"""create user preferences table

Revision ID: 514893182b42
Revises: cc6d66c5fd59
Create Date: 2026-06-06 12:48:13.227815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514893182b42'
down_revision: Union[str, None] = 'cc6d66c5fd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencias_usuarios',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tema', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_preferencias_usuarios_empresa_id'), 'preferencias_usuarios', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferencias_usuarios_empresa_id'), table_name='preferencias_usuarios')
    op.drop_table('preferencias_usuarios')
    # ### end Alembic commands ###
