"""catalogo_admin

Revision ID: 76e18683cd19
Revises: e4a7b4eca0ab
Create Date: 2026-06-12 07:39:52.397727

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '76e18683cd19'
down_revision: str | None = 'e4a7b4eca0ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_articulos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_categorias_articulos_empresa_nombre')
    )
    op.create_index(op.f('ix_categorias_articulos_empresa_id'), 'categorias_articulos', ['empresa_id'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('sede', 'planta', 'area', 'seccion', name='locationtype'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['ubicaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ubicaciones_empresa_parent', 'ubicaciones', ['empresa_id', 'parent_id'], unique=False)
    op.create_index(op.f('ix_ubicaciones_empresa_id'), 'ubicaciones', ['empresa_id'], unique=False)
    op.create_table('articulos_catalogo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_articulos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_articulos_catalogo_empresa_categoria', 'articulos_catalogo', ['empresa_id', 'categoria_id'], unique=False)
    op.create_index(op.f('ix_articulos_catalogo_empresa_id'), 'articulos_catalogo', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articulos_catalogo_empresa_id'), table_name='articulos_catalogo')
    op.drop_index('idx_articulos_catalogo_empresa_categoria', table_name='articulos_catalogo')
    op.drop_table('articulos_catalogo')
    op.drop_index(op.f('ix_ubicaciones_empresa_id'), table_name='ubicaciones')
    op.drop_index('idx_ubicaciones_empresa_parent', table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_categorias_articulos_empresa_id'), table_name='categorias_articulos')
    op.drop_table('categorias_articulos')
    # ### end Alembic commands ###
