"""add_version_to_preferences

Revision ID: 7da6e3c7cab0
Revises: 10468db73cf1
Create Date: 2026-06-13 07:41:02.427869

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da6e3c7cab0'
down_revision: str | None = '10468db73cf1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferencias_usuarios', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferencias_usuarios', 'version')
    # ### end Alembic commands ###
