"""add_activo_id_to_failure_report

Revision ID: 7ee9f62274a0
Revises: f1a2b3c4d5e6
Create Date: 2026-06-29 02:14:50.713250

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee9f62274a0'
down_revision: str | None = 'f1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportes_fallas', sa.Column('activo_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reportes_fallas', 'activos', ['activo_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reportes_fallas', type_='foreignkey')
    op.drop_column('reportes_fallas', 'activo_id')
    # ### end Alembic commands ###
