"""create_system_audits_table

Revision ID: 823874b35563
Revises: 7da6e3c7cab0
Create Date: 2026-06-25 00:01:26.186793

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823874b35563'
down_revision: str | None = '7da6e3c7cab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audits_empresa_id'), 'system_audits', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_system_audits_id'), 'system_audits', ['id'], unique=False)
    op.create_index(op.f('ix_system_audits_usuario_id'), 'system_audits', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_audits_usuario_id'), table_name='system_audits')
    op.drop_index(op.f('ix_system_audits_id'), table_name='system_audits')
    op.drop_index(op.f('ix_system_audits_empresa_id'), table_name='system_audits')
    op.drop_table('system_audits')
    # ### end Alembic commands ###
