"""plan_execution — tabla planes_ejecuciones

Revision ID: a1b2c3d4e5f6
Revises: 7da6e3c7cab0
Create Date: 2026-06-27 16:45:00.000000

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: str | None = 'b77f2c9dfbb4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ponytail: plan_id sin FK — planes_mantenimiento está en otra rama.
    #            orden_trabajo_id sin FK — WorkOrder en otra rama.
    op.create_table('planes_ejecuciones',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('empresa_id', sa.Uuid(), nullable=False),
        sa.Column('plan_id', sa.Uuid(), nullable=False),
        sa.Column('orden_trabajo_id', sa.Uuid(), nullable=True),
        sa.Column('fecha_ejecucion', sa.DateTime(timezone=True), nullable=False),
        sa.Column('observaciones', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_planes_ejecuciones_empresa_id'), 'planes_ejecuciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_planes_ejecuciones_plan_id'), 'planes_ejecuciones', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planes_ejecuciones_plan_id'), table_name='planes_ejecuciones')
    op.drop_index(op.f('ix_planes_ejecuciones_empresa_id'), table_name='planes_ejecuciones')
    op.drop_table('planes_ejecuciones')
    # ### end Alembic commands ###
