"""create_used_parts_table

Revision ID: c28c721fa3e3
Revises: 7da6e3c7cab0
Create Date: 2026-06-26 18:26:37.844779

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28c721fa3e3'
down_revision: str | None = '7da6e3c7cab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repuestos_utilizados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intervencion_id', sa.Uuid(), nullable=False),
    sa.Column('repuesto_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_usada', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repuestos_utilizados_empresa_id'), 'repuestos_utilizados', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repuestos_utilizados_empresa_id'), table_name='repuestos_utilizados')
    op.drop_table('repuestos_utilizados')
    # ### end Alembic commands ###
