"""add_version_to_article_category

Revision ID: d95f288bf0b9
Revises: 7da6e3c7cab0
Create Date: 2026-06-27 02:18:24.908301

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd95f288bf0b9'
down_revision: str | None = '7da6e3c7cab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Agrega columna version a categorias_articulos para optimistic locking."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'categorias_articulos',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Elimina columna version de categorias_articulos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias_articulos', 'version')
    # ### end Alembic commands ###
