"""plataforma_auth

Revision ID: e4a7b4eca0ab
Revises: 
Create Date: 2026-06-12 07:39:41.076924

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e4a7b4eca0ab'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('max_activos', sa.Integer(), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('precio_mensual_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'suspendida', 'cancelada', name='companystatus'), nullable=False),
    sa.Column('trial_hasta', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_suscripcion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_slug'), 'empresas', ['slug'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_roles_empresa_nombre')
    )
    op.create_index(op.f('ix_roles_empresa_id'), 'roles', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_usuarios_empresa_email')
    )
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('modulo', sa.Enum('activos', 'mantenimiento', 'inventario', 'reportes', 'administracion', 'preferencias', name='permissionmodule'), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=False),
    sa.Column('puede_crear', sa.Boolean(), nullable=False),
    sa.Column('puede_editar', sa.Boolean(), nullable=False),
    sa.Column('puede_eliminar', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'rol_id', 'modulo', name='uq_permisos_empresa_rol_modulo')
    )
    op.create_index(op.f('ix_permisos_empresa_id'), 'permisos', ['empresa_id'], unique=False)
    op.create_table('preferencias_usuarios',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tema', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_preferencias_usuarios_empresa_id'), 'preferencias_usuarios', ['empresa_id'], unique=False)
    op.create_table('roles_usuarios',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_usuarios')
    op.drop_index(op.f('ix_preferencias_usuarios_empresa_id'), table_name='preferencias_usuarios')
    op.drop_table('preferencias_usuarios')
    op.drop_index(op.f('ix_permisos_empresa_id'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_empresa_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_empresas_slug'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_table('planes_suscripcion')
    # ### end Alembic commands ###
